class FoodModel {
  final String recipe;
  final String recipeApp;
  final String imagGlav;
  final String title;
  final String description;
  final String time1;
  final String timeDes1;
  final String time2;
  final String timeDes2;
  final String time3;
  final String timeDes3;
  final String? time4;
  final String? timeDes4;
  final String? time5;
  final String? timeDes5;
  final String? imageIngredient;
  final String ingr1;
  final String ingr2;
  final String ingr3;
  final String ingr4;
  final String ingr5;
  final String? ingr6;
  final String? ingr7;
  final String? ingr8;
  final String? ingr9;
  final String? ingr10;
  final String? ingr11;
  final String? ingr12;
  final String? ingr13;
  final String? ingr14;
  final String? ingr15;
  final String? ingr16;
  final String? ingr17;
  final String? ingr18;
  final String step1;
  final String descriptionStep1;
  final String? imageStep1;
  final String? step2;
  final String? descriptionStep2;
  final String? imageStep2;
  final String? step3;
  final String? descriptionStep3;
  final String? imageStep3;
  final String? step4;
  final String? descriptionStep4;
  final String? imageStep4;
  final String? step5;
  final String? descriptionStep5;
  final String? imageStep5;
  final String? randoName;
  final String? randoDescription;
  final String? calories;
  final String? fat;
  final String? carbs;
  final String? protein;

  FoodModel({
    required this.recipe,
    required this.recipeApp,
    required this.imagGlav,
    required this.title,
    required this.description,
    required this.time1,
    required this.timeDes1,
    required this.time2,
    required this.timeDes2,
    required this.time3,
    required this.timeDes3,
    required this.time4,
    required this.timeDes4,
    required this.time5,
    required this.timeDes5,
    required this.imageIngredient,
    required this.ingr1,
    required this.ingr2,
    required this.ingr3,
    required this.ingr4,
    required this.ingr5,
    required this.ingr6,
    required this.ingr7,
    required this.ingr8,
    required this.ingr9,
    required this.ingr10,
    required this.ingr11,
    required this.ingr12,
    required this.ingr13,
    required this.ingr14,
    required this.ingr15,
    required this.ingr16,
    required this.ingr17,
    required this.ingr18,
    required this.step1,
    required this.descriptionStep1,
    required this.imageStep1,
    required this.step2,
    required this.descriptionStep2,
    required this.imageStep2,
    required this.step3,
    required this.descriptionStep3,
    required this.imageStep3,
    required this.step4,
    required this.descriptionStep4,
    required this.imageStep4,
    required this.step5,
    required this.descriptionStep5,
    required this.imageStep5,
    required this.randoName,
    required this.randoDescription,
    required this.calories,
    required this.fat,
    required this.carbs,
    required this.protein,
  });
}

List<FoodModel> foodModelList = [
  FoodModel(
    recipe: '1st recipe',
    recipeApp: 'Recipe 1',
    imagGlav: 'assets/images/food1.png',
    title: 'One-Pan Chicken Parmesan Pasta',
    description:
        'This chicken Parmesan pasta uses the one-pot pasta method to cook your noodles, chicken and sauce all in one skillet for a fast and easy dinner with minimal cleanup.',
    time1: 'Active Time:',
    timeDes1: '45 mins',
    time2: 'Total Time:',
    timeDes2: '45 mins',
    time3: 'Servings:',
    timeDes3: '4',
    time4: 'Yield:',
    timeDes4: '4 servings',
    time5: null,
    timeDes5: null,
    imageIngredient: null,
    ingr1: '2 tablespoons extra-virgin olive oil, divided',
    ingr2: '¼ cup whole-wheat panko breadcrumbs',
    ingr3: '1 tablespoon plus 1 teaspoon minced garlic, divided',
    ingr4:
        '1 pound boneless, skinless chicken breast, cut into 1/2-inch pieces',
    ingr5: '1 teaspoon Italian seasoning',
    ingr6: '¼ teaspoon salt',
    ingr7: '3 cups low-sodium chicken broth',
    ingr8: '1 ½ cups crushed tomatoes',
    ingr9: '8 ounces whole-wheat penne',
    ingr10: '½ cup shredded mozzarella cheese',
    ingr11: '¼ cup shredded Parmesan cheese',
    ingr12: '¼ cup chopped fresh basil',
    ingr13: null,
    ingr14: null,
    ingr15: null,
    ingr16: null,
    ingr17: null,
    ingr18: null,
    step1: 'Step 1',
    descriptionStep1:
        'Heat 1 tablespoon oil in a large broiler-safe skillet over medium-high heat. Add panko and 1 teaspoon garlic. Cook, stirring, until the panko is golden brown, 1 to 2 minutes. Transfer to a small bowl and set aside. Wipe out the pan.',
    imageStep1: null,
    step2: 'Step 2',
    descriptionStep2:
        'Heat the remaining 1 tablespoon oil in the pan over medium-high heat. Add chicken, Italian seasoning, salt and the remaining 1 tablespoon garlic. Cook, stirring frequently, until the chicken is no longer pink on the outside, about 2 minutes. Add broth, tomatoes and penne. Bring to a boil and cook, uncovered, stirring frequently, until the penne is cooked and the sauce has reduced and thickened, 15 to 20 minutes.',
    imageStep2: null,
    step3: 'Step 3',
    descriptionStep3:
        'Meanwhile, position an oven rack in the upper third of the oven. Preheat the broiler to high. When the pasta is cooked, sprinkle mozzarella over the penne mixture. Place the pan under the broiler; broil until the mozzarella is bubbling and beginning to brown, about 1 minute. Top with the panko mixture, Parmesan and basil.',
    imageStep3: null,
    step4: null,
    descriptionStep4: null,
    imageStep4: null,
    step5: null,
    descriptionStep5: null,
    imageStep5: null,
    randoName: 'Equipment',
    randoDescription: 'Large ovenproof skillet',
    calories: '538',
    fat: '17g',
    carbs: '56g',
    protein: '41g',
  ),
  FoodModel(
    recipe: '2nd recipe',
    recipeApp: 'Recipe 2',
    imagGlav: 'assets/images/food2.png',
    title: 'Sheet-Pan Chicken Fajitas',
    description:
        'One sheet pan is all you\'ll need to whip up this chicken fajita recipe. They\'re quick and easy to make and cleanup is even faster!',
    time1: 'Active Time:',
    timeDes1: '20 mins',
    time2: 'Additional Time:',
    timeDes2: '20 mins',
    time3: 'Total Time:',
    timeDes3: '40 mins',
    time4: 'Servings:',
    timeDes4: '4',
    time5: 'Yield:',
    timeDes5: '4 servings',
    imageIngredient: null,
    ingr1: '1 pound boneless, skinless chicken breasts',
    ingr2: '2 tablespoons extra-virgin olive oil',
    ingr3: '1 tablespoon chili powder',
    ingr4: '2 teaspoons ground cumin',
    ingr5: '1 teaspoon garlic powder',
    ingr6: '¾ teaspoon salt',
    ingr7: '1 large red bell pepper, sliced',
    ingr8: '1 large yellow bell pepper, sliced',
    ingr9: '2 cups sliced red or yellow onion (about 1 large)',
    ingr10: '1 tablespoon lime juice',
    ingr11: '8 corn tortillas, warmed',
    ingr12:
        'Lime wedges, cilantro, sour cream, avocado and/or pico de gallo for serving',
    ingr13: null,
    ingr14: null,
    ingr15: null,
    ingr16: null,
    ingr17: null,
    ingr18: null,
    step1: 'Step 1',
    descriptionStep1:
        'Preheat oven to 400°F. Coat a large rimmed baking sheet with cooking spray.',
    imageStep1: null,
    step2: 'Step 2',
    descriptionStep2:
        'Cut chicken breasts in half horizontally, then slice crosswise into strips. Combine oil, chili powder, cumin, garlic powder and salt in a large bowl. Add the chicken and stir to coat with the spice mixture. Add bell peppers and onion and stir to combine. Transfer the chicken and vegetables to the prepared baking sheet and spread in an even layer.',
    imageStep2: null,
    step3: 'Step 3',
    descriptionStep3:
        'Roast on the middle rack for 15 minutes. Leave the pan there and turn the broiler to high. Broil until the chicken is cooked through and the vegetables are browning in spots, about 5 minutes more. Remove from oven. Stir in lime juice.',
    imageStep3: null,
    step4: 'Step 4',
    descriptionStep4:
        'Serve the chicken and vegetables in warmed tortillas accompanied by lime wedges and topped with cilantro, sour cream, avocado and/or pico de gallo, if desired. ',
    imageStep4: null,
    step5: null,
    descriptionStep5: null,
    imageStep5: null,
    randoName: null,
    randoDescription: null,
    calories: '357',
    fat: '12g',
    carbs: '33g',
    protein: '30g',
  ),
  FoodModel(
    recipe: '3rd recipe',
    recipeApp: 'Recipe 3',
    imagGlav: 'assets/images/food3.png',
    title: 'Philly Cheese Steak Sloppy Joes',
    description:
        'Two of our favorite comfort-food sandwiches join forces in these family-friendly dinner sandwiches. We found that softer buns make this easier to eat, and it\'s all the better when wrapped takeout-style in a sheet of foil.',
    time1: 'Prep Time:',
    timeDes1: '20 mins',
    time2: 'Total Time:',
    timeDes2: '20 mins',
    time3: 'Servings:',
    timeDes3: '4',
    time4: 'Yield:',
    timeDes4: '4 subs',
    time5: null,
    timeDes5: null,
    imageIngredient: null,
    ingr1: '2 teaspoons organic canola oil or avocado oil',
    ingr2: '1 pound lean ground beef',
    ingr3: '1 teaspoon dried oregano',
    ingr4: '¼ teaspoon salt',
    ingr5: '1 cup no-salt-added tomato sauce',
    ingr6: '1 cup Sautéed Peppers & Onions (see associated recipe)',
    ingr7: '4 (6 inch) whole-wheat sub rolls, split',
    ingr8: '4 slices reduced-sodium provolone cheese',
    ingr9: null,
    ingr10: null,
    ingr11: null,
    ingr12: null,
    ingr13: null,
    ingr14: null,
    ingr15: null,
    ingr16: null,
    ingr17: null,
    ingr18: null,
    step1: 'Step 1',
    descriptionStep1:
        'Arrange oven rack in upper third of the oven. Preheat broiler. Line a baking sheet with foil.',
    imageStep1: null,
    step2: 'Step 2',
    descriptionStep2:
        ' Heat oil in a large skillet over medium-high heat. Add beef, oregano and salt; cook, crumbling with a wooden spoon, until cooked through, 4 to 6 minutes. Add tomato sauce and cook until bubbling, 1 to 2 minutes.',
    imageStep2: null,
    step3: 'Step 3',
    descriptionStep3:
        'Meanwhile, warm peppers and onions in a small skillet over medium heat, stirring often. (Alternatively, microwave for 1 minute to reheat.)',
    imageStep3: null,
    step4: 'Step 4',
    descriptionStep4:
        'Lay rolls, split-side open, on the prepared baking sheet. Broil, rotating the pan as necessary, until just starting to brown and toast, 1 to 2 minutes. Remove from the oven.',
    imageStep4: null,
    step5: 'Step 5',
    descriptionStep5:
        'Top toasted buns with the beef mixture, dividing evenly. Top with the peppers and onions and then cheese. Broil just until the cheese is melted, 30 seconds to 1 minute. Wrap each sub in foil until ready to eat. Serve hot.',
    imageStep5: null,
    randoName: null,
    randoDescription: null,
    calories: '413',
    fat: '20g',
    carbs: '29g',
    protein: '30g',
  ),
  FoodModel(
    recipe: '4th recipe',
    recipeApp: 'Recipe 4',
    imagGlav: 'assets/images/food4.png',
    title: '20-Minute Creamy Chicken Skillet with Italian Seasoning',
    description:
        'Chicken cutlets cook quickly and are highlighted with a creamy sauce made with tomatoes, zucchini and Italian seasoning. This recipe is sure to become a new weeknight favorite the whole family will love. Serve it with whole-wheat pasta or rice to make it a meal.',
    time1: 'Prep Time:',
    timeDes1: '20 mins',
    time2: 'Total Time:',
    timeDes2: '20 mins',
    time3: 'Servings:',
    timeDes3: '4',
    time4: 'Yield:',
    timeDes4: '4 servings',
    time5: null,
    timeDes5: null,
    imageIngredient: null,
    ingr1: '1 pound chicken cutlets',
    ingr2: '¼ teaspoon salt, divided',
    ingr3: '¼ teaspoon ground pepper, divided',
    ingr4: '2 tablespoons extra-virgin olive oil, divided',
    ingr5: '1 medium zucchini, halved lengthwise and thinly sliced',
    ingr6: '½ cup chopped onion',
    ingr7: '⅓ cup dry white wine',
    ingr8: '1 (15-ounce) can no-salt-added diced tomatoes',
    ingr9: '2 ounces cream cheese, cut into cubes',
    ingr10: '1 teaspoon Italian seasoning',
    ingr11: '½ teaspoon garlic powder',
    ingr12: '¼ cup chopped fresh basil',
    ingr13: null,
    ingr14: null,
    ingr15: null,
    ingr16: null,
    ingr17: null,
    ingr18: null,
    step1: 'Step 1',
    descriptionStep1:
        'Sprinkle chicken with 1/8 teaspoon each salt and pepper. Heat 1 tablespoon oil in a large skillet over medium heat. Add the chicken and cook, turning once, until browned and an instant-read thermometer inserted into the thickest part registers 165 degrees F. Transfer to a plate.',
    imageStep1: null,
    step2: 'Step 2',
    descriptionStep2:
        'Add the remaining 1 tablespoon oil, zucchini and onion to the pan. Cook, stirring, until starting to soften, about 2 minutes. Increase heat to medium-high and add wine. Cook, scraping up any browned bits, until the liquid has mostly evaporated, about 2 minutes. Add tomatoes, cream cheese, Italian seasoning, garlic powder and the remaining 1/8 teaspoon each salt and pepper. Bring to a simmer and cook, stirring to melt the cream cheese, for 5 minutes. Return the chicken to the pan and turn to coat with the sauce. Serve topped with basil.',
    imageStep2: null,
    step3: null,
    descriptionStep3: null,
    imageStep3: null,
    step4: null,
    descriptionStep4: null,
    imageStep4: null,
    step5: null,
    descriptionStep5: null,
    imageStep5: null,
    randoName: null,
    randoDescription: null,
    calories: '301',
    fat: '15g',
    carbs: '9g',
    protein: '27g',
  ),
  FoodModel(
    recipe: '5th recipe',
    recipeApp: 'Recipe 5',
    imagGlav: 'assets/images/food5.png',
    title: 'Mini Meatloaves with Green Beans & Potatoes',
    description:
        'This healthy meatloaf recipe and side dishes are all made in the oven on two sheet pans so that everything\'s ready for the dinner table at the same time. The potatoes go into the oven first to start roasting while the mini meatloaves and green beans are prepped and added to the oven partway through.',
    time1: 'Cook Time:',
    timeDes1: '20 mins',
    time2: 'Additional Time:',
    timeDes2: '20 mins',
    time3: 'Total Time:',
    timeDes3: '40 mins',
    time4: 'Servings:',
    timeDes4: '4',
    time5: 'Yield:',
    timeDes5: '4 servings',
    imageIngredient: null,
    ingr1: '½ teaspoon paprika',
    ingr2: '½ teaspoon garlic powder, divided',
    ingr3: '¾ teaspoon salt, divided',
    ingr4: '¾ teaspoon ground pepper, divided',
    ingr5:
        '1 pound Yukon Gold or red potatoes, scrubbed and cut into 1-inch wedges',
    ingr6: '2 tablespoons extra-virgin olive oil, divided',
    ingr7: '1 pound lean (90% or leaner) ground beef',
    ingr8: '1 large egg, lightly beaten',
    ingr9: '¼ cup finely chopped onion',
    ingr10: '¼ cup Italian-seasoned panko breadcrumbs',
    ingr11: '3 tablespoons ketchup, divided',
    ingr12: '1 tablespoon Worcestershire sauce',
    ingr13: '1 pound green beans, trimmed',
    ingr14: null,
    ingr15: null,
    ingr16: null,
    ingr17: null,
    ingr18: null,
    step1: 'Step 1',
    descriptionStep1:
        'Position racks in upper and lower thirds of oven; preheat to 425 degrees F. Coat 2 large rimmed baking sheets with cooking spray.',
    imageStep1: null,
    step2: 'Step 2',
    descriptionStep2:
        'Combine paprika and 1/4 teaspoon each garlic powder, salt and pepper in a large bowl. Add potatoes and toss to coat. Drizzle with 1 tablespoon oil, toss again, then spread the potatoes in a single layer on one of the prepared baking sheets. (Reserve the bowl.) Place on the lower rack to roast for 10 minutes.',
    imageStep2: null,
    step3: 'Step 3',
    descriptionStep3:
        'Meanwhile, combine beef, egg, onion, breadcrumbs, 2 tablespoons ketchup, Worcestershire and 1/4 teaspoon each garlic powder, salt and pepper in the large bowl. Form the mixture into 4 small loaves about 2 by 4 inches each and place on the other prepared baking sheet. Brush the tops with the remaining 1 tablespoon ketchup. Remove the potatoes from the oven and put the meatloaves on the lower rack.',
    imageStep3: null,
    step4: 'Step 4',
    descriptionStep4:
        'Toss green beans with the remaining 1 tablespoon oil and 1/4 teaspoon each salt and pepper. Move the potatoes to one side of their pan and add the green beans to the other side. Roast the vegetables on the upper rack until the green beans are tender and an instant-read thermometer inserted into the center of the meatloaves registers 165 degrees F, 20 to 30 minutes more.',
    imageStep4: null,
    step5: null,
    descriptionStep5: null,
    imageStep5: null,
    randoName: 'Tips',
    randoDescription:
        'Easy cleanup: Recipes that require cooking spray can leave behind a sticky residue that can be hard to clean. To save time and keep your baking sheet looking fresh, line it with a layer of foil before you apply the cooking spray.',
    calories: '436',
    fat: '20g',
    carbs: '36g',
    protein: '29',
  ),
  FoodModel(
    recipe: '6th recipe',
    recipeApp: 'Recipe 6',
    imagGlav: 'assets/images/food6.png',
    title: 'Easy Chicken Enchilada Casserole',
    description:
        'Casseroles make perfect meal-prep dinners, and this enchilada version is no exception. The whole casserole can be built and left to hang out in the refrigerator for up to three days—just bake it off on a busy night and you have a healthy, easy dinner on the table in no time. The quick homemade enchilada sauce in this recipe is great when you don\'t have any of the canned sauce on hand; just season crushed tomatoes with spices and salt for an instant enchilada sauce.',
    time1: 'Prep Time:',
    timeDes1: '20 mins',
    time2: 'Additional Time:',
    timeDes2: '35 mins',
    time3: 'Total Time:',
    timeDes3: '55 mins',
    time4: 'Servings:',
    timeDes4: '6',
    time5: 'Yield:',
    timeDes5: '1 casserole',
    imageIngredient: null,
    ingr1: '1 (28 ounce) can crushed tomatoes (3 cups)',
    ingr2: '2 tablespoons ground cumin',
    ingr3: '1/2-1 teaspoon ground chipotle chile powder',
    ingr4: '¼ teaspoon salt',
    ingr5: '8 corn tortillas, cut into wedges',
    ingr6: '1 (15 ounce) can black beans, rinsed and drained',
    ingr7:
        '1 cup chopped Meal-Prep Sheet-Pan Chicken Thighs (see associated recipe)',
    ingr8: '2 cups Sautéed Peppers & Onions (see associated recipe)',
    ingr9: '1 ½ cups shredded Mexican cheese blend (6 ounces), divided',
    ingr10: null,
    ingr11: null,
    ingr12: null,
    ingr13: null,
    ingr14: null,
    ingr15: null,
    ingr16: null,
    ingr17: null,
    ingr18: null,
    step1: 'Step 1',
    descriptionStep1:
        'Stir tomatoes, cumin, chile powder and salt together in a medium bowl. Coat a 7- or 8-by-11-inch casserole dish with cooking spray. Spoon 1/2 cup of the tomato sauce into the bottom of the prepared dish. Arrange 1/3 of the tortilla wedges over the tomato sauce. Top with half of the beans, half of the chicken and half of the pepper mixture. Top with 1 cup sauce and 1/2 cup cheese.',
    imageStep1: null,
    step2: 'Step 2',
    descriptionStep2:
        'Layer on half the remaining tortillas. Top with the remaining beans, chicken and pepper mixture. Top with 1 cup of the sauce and 1/2 cup cheese. Layer on the remaining tortillas, followed by the remaining sauce (about 1/3 cup). Sprinkle with the remaining 1/2 cup cheese. Cover with foil and refrigerate until ready to cook, up to 3 days.',
    imageStep2: null,
    step3: 'Step 3',
    descriptionStep3:
        'Preheat oven to 375 degrees F. Bake the casserole, uncovered, until hot and bubbling, 35 to 40 minutes. (Alternatively, microwave the casserole, covered with wax paper, on Medium-High until steaming hot, 12 to 15 minutes.) Serve hot.',
    imageStep3: null,
    step4: null,
    descriptionStep4: null,
    imageStep4: null,
    step5: null,
    descriptionStep5: null,
    imageStep5: null,
    randoName: 'To make ahead',
    randoDescription:
        'Prepare through Step 2 and refrigerate for up to 3 days.',
    calories: '365',
    fat: '15g',
    carbs: '39g',
    protein: '21g',
  ),
  FoodModel(
    recipe: '7th recipe',
    recipeApp: 'Recipe 7',
    imagGlav: 'assets/images/food7.png',
    title: 'Taco Lettuce Wraps',
    description:
        'Don\'t limit yourself to lettuce for this low-carb, gluten-free taco lettuce wrap recipe—any fresh green sturdy enough to wrap around 1/2 cup of filling works.',
    time1: 'Prep Time:',
    timeDes1: '30 mins',
    time2: 'Total Time:',
    timeDes2: '30 mins',
    time3: 'Servings:',
    timeDes3: '4',
    time4: 'Yield:',
    timeDes4: '4 servings',
    time5: null,
    timeDes5: null,
    imageIngredient: null,
    ingr1:
        '8 small iceberg or romaine lettuce leaves or 4 large, cut in half crosswise',
    ingr2: '1 tablespoon canola oil',
    ingr3: '1 pound lean ground beef',
    ingr4: '¼ teaspoon salt',
    ingr5: '5 tablespoons prepared salsa',
    ingr6: '1 tablespoon rice vinegar',
    ingr7: '1 ½ teaspoons ground cumin',
    ingr8: '1 cup diced avocado',
    ingr9: '1 cup julienned jícama (see Tip)',
    ingr10: '¼ cup finely diced red onion',
    ingr11: null,
    ingr12: null,
    ingr13: null,
    ingr14: null,
    ingr15: null,
    ingr16: null,
    ingr17: null,
    ingr18: null,
    step1: 'Step 1',
    descriptionStep1:
        'Wash and dry lettuce leaves well and cut out any tough ribs.',
    imageStep1: null,
    step2: 'Step 2',
    descriptionStep2:
        'Heat oil in a large nonstick skillet over medium-high heat. Add ground beef, season with salt and cook, stirring often, until cooked through, 4 to 6 minutes.',
    imageStep2: null,
    step3: 'Step 3',
    descriptionStep3:
        'Meanwhile, whisk salsa, vinegar and cumin in a small bowl.',
    imageStep3: null,
    step4: 'Step 4',
    descriptionStep4:
        'Remove the pan from the heat, add the salsa mixture and stir to combine. Serve in the lettuce leaves, topped with avocado, jicama and onion.',
    imageStep4: null,
    step5: null,
    descriptionStep5: null,
    imageStep5: null,
    randoName: 'Tips',
    randoDescription:
        'Jícama is a round root vegetable with thin brown skin and white crunchy flesh. It has a slightly sweet and nutty flavor. To peel it, use a small, sharp knife or vegetable peeler, making sure to remove both the papery brown skin and the layer of fibrous flesh just underneath.',
    calories: '291',
    fat: '19g',
    carbs: '8g',
    protein: '23g',
  ),
  FoodModel(
    recipe: '8th recipe',
    recipeApp: 'Recipe 8',
    imagGlav: 'assets/images/food8.png',
    title: 'Healthy Oven-Fried Pork Chops',
    description:
        'These whole-wheat panko breadcrumb-coated pork chops get just as crispy as fried chops, but they\'re baked. Serve with steamed broccoli and baked sweet potato for a satisfying, healthy weeknight dinner.',
    time1: 'Prep Time:',
    timeDes1: '15 mins',
    time2: 'Additional Time:',
    timeDes2: '20 mins',
    time3: 'Total Time:',
    timeDes3: '35 mins',
    time4: 'Servings:',
    timeDes4: '4',
    time5: 'Yield:',
    timeDes5: '4 servings',
    imageIngredient: null,
    ingr1: 'Cooking spray',
    ingr2: '¼ cup all-purpose flour',
    ingr3: '1 large egg, lightly beaten',
    ingr4: '1 teaspoon Dijon mustard',
    ingr5: '¾ cup whole-wheat panko breadcrumbs',
    ingr6: '1 teaspoon ground pepper',
    ingr7: '½ teaspoon kosher salt',
    ingr8: '4 (4 ounce) 3/4-inch-thick boneless pork chops',
    ingr9: null,
    ingr10: null,
    ingr11: null,
    ingr12: null,
    ingr13: null,
    ingr14: null,
    ingr15: null,
    ingr16: null,
    ingr17: null,
    ingr18: null,
    step1: 'Step 1',
    descriptionStep1:
        'Preheat oven to 400°F. Place a wire rack on a large rimmed baking sheet and coat with cooking spray. Place flour in a shallow dish. Combine beaten egg and mustard in another small dish. Combine panko and pepper in a third shallow dish.',
    imageStep1: null,
    step2: 'Step 2',
    descriptionStep2:
        'Sprinkle salt over both sides of the pork. Dredge each pork chop in flour, shaking off the excess. Coat in egg mixture, then panko, pressing to adhere. Place on the prepared rack. Coat the pork chops with cooking spray. Bake until the chops are beginning to brown and are cooked throughout (an instant-read thermometer inserted in the center should register 145°F), 18 to 20 minutes.',
    imageStep2: null,
    step3: null,
    descriptionStep3: null,
    imageStep3: null,
    step4: null,
    descriptionStep4: null,
    imageStep4: null,
    step5: null,
    descriptionStep5: null,
    imageStep5: null,
    randoName: 'Equipment',
    randoDescription: 'Wire rack, large rimmed baking sheet',
    calories: '194',
    fat: '6g',
    carbs: '12g',
    protein: '22g',
  ),
  FoodModel(
    recipe: '9th recipe',
    recipeApp: 'Recipe 9',
    imagGlav: 'assets/images/food9.png',
    title: 'Spinach & Tuna Noodle Casserole',
    description:
        'Homemade mushroom sauce kicks the can of soup out of the picture in this veggie-centric, healthy riff on a classic tuna-noodle casserole recipe. Serve with steamed green beans.',
    time1: 'Cook Time:',
    timeDes1: '50 mins',
    time2: 'Additional Time:',
    timeDes2: '20 mins',
    time3: 'Total Time:',
    timeDes3: '1 hr 10 mins',
    time4: 'Servings:',
    timeDes4: '8',
    time5: 'Yield:',
    timeDes5: '8 servings',
    imageIngredient: null,
    ingr1: '6 ounces egg noodles, preferably whole-wheat (4 1/2 cups dry)',
    ingr2: '3 tablespoons butter',
    ingr3: '2 tablespoons extra-virgin olive oil, divided',
    ingr4: '1 cup finely chopped onion',
    ingr5: '½ cup finely chopped celery',
    ingr6: '10 ounces mushrooms, sliced',
    ingr7: '3 tablespoons dry sherry',
    ingr8: '2 teaspoons reduced-sodium soy sauce',
    ingr9: '½ teaspoon kosher salt',
    ingr10: '½ teaspoon ground pepper',
    ingr11: '¼ cup white whole-wheat flour or all-purpose flour',
    ingr12: '2 cups low-sodium chicken broth, divided',
    ingr13: '1 cup reduced-fat milk',
    ingr14: '2 teaspoons Dijon mustard',
    ingr15:
        '2 5-ounce cans chunk light tuna in olive oil (see Tips), drained and flaked',
    ingr16: '10 cups baby spinach or 4 cups frozen chopped spinach (thawed)',
    ingr17: '1 cup coarse fresh breadcrumbs (see Tips), preferably whole-wheat',
    ingr18: '¾ cup grated aged Cheddar cheese',
    step1: 'Step 1',
    descriptionStep1:
        'Preheat oven to 375 degrees F. Coat a 9-by-13-inch pan (or similar-size 3-quart baking dish) with cooking spray.',
    imageStep1: null,
    step2: 'Step 2',
    descriptionStep2:
        'Bring a large pot of water to a boil and cook noodles according to package instructions. Drain and set aside. Dry the pot.',
    imageStep2: null,
    step3: 'Step 3',
    descriptionStep3:
        'Heat butter and 1 tablespoon oil in the pot over medium heat until the butter is melted. Add onion and celery; cook, stirring occasionally, until soft, about 5 minutes. Add mushrooms and cook, stirring occasionally, until their liquid evaporates, 3 to 5 minutes. Stir in sherry, soy sauce, salt and pepper and cook until almost all the liquid has evaporated, 2 to 4 minutes more. Sprinkle flour over the vegetables, stir to coat and cook for 30 seconds.',
    imageStep3: null,
    step4: 'Step 4',
    descriptionStep4:
        'Increase heat to high, add 1/2 cup broth and stir until starting to boil. Add the remaining 1 1/2 cups broth, milk and mustard; bring to a boil and cook, stirring often, until the sauce thickens, about 2 minutes. Add tuna, spinach and the reserved noodles; cook, gently stirring often, until heated through, about 3 minutes. Transfer to the prepared baking dish.',
    imageStep4: null,
    step5: 'Step 5',
    descriptionStep5:
        'Combine breadcrumbs and cheese in a small bowl. Stir in the remaining 1 tablespoon oil and sprinkle over the casserole. Bake until the sauce is bubbling and the topping is golden brown, 20 to 25 minutes.',
    imageStep5: null,
    randoName: 'Tips',
    randoDescription:
        '''Make Ahead Tip: Prepare through Step 4; refrigerate for up to 1 day. Let stand at room temperature for 30 minutes and finish Step 5 before baking.

For sustainable chunk light tuna, look for the blue Certified Sustainable Seafood label from the Marine Stewardship Council. The certification means the tuna was troll- or pole-and-line caught, which are sustainable for the fish and the environment. We call for chunk light tuna because it's significantly lower in mercury than albacore (“solid white” tuna)--making it a better choice for health, especially for pregnant women, nursing mothers and children. According to the FDA and EPA, these at-risk groups should still limit their consumption of lower-mercury tuna to 12 ounces a week. The Environmental Working Group (EWG) suggests limiting it even more. (For more info, see the EWG's Seafood Calculator at ewg.org.)

Don't toss your stale bread! Make your own breadcrumbs. Trim off any tough crusts and tear or cut the bread into pieces. Process in a food processor until coarse or fine crumbs form. Use right away or freeze in an airtight container for up to 6 months. Thaw before using. One slice of bread makes about 1/2 cup fresh coarse breadcrumbs.''',
    calories: '323',
    fat: '16g',
    carbs: '28g',
    protein: '18g',
  ),
  FoodModel(
    recipe: '10th recipe',
    recipeApp: 'Recipe 10',
    imagGlav: 'assets/images/food10.png',
    title: 'Cheeseburger Casserole',
    description:
        'If you love a classic cheeseburger with all the fixings, you’ll love this family-friendly cheeseburger casserole. Rotini pasta picks up all the flavors of this comforting dish, but any shape pasta you have in your pantry will work well. We love the crunch shredded fresh lettuce offers, but feel free to mix it up with another green like spinach or kale, or top your casserole with Swiss cheese and sautéed mushrooms for a different spin.',
    time1: 'Active Time:',
    timeDes1: '30 mins',
    time2: 'Total Time:',
    timeDes2: '30 mins',
    time3: 'Servings:',
    timeDes3: '6 servings',
    time4: null,
    timeDes4: null,
    time5: null,
    timeDes5: null,
    imageIngredient: null,
    ingr1: '8 ounces whole-wheat rotini',
    ingr2: '1 tablespoon extra-virgin olive oil',
    ingr3: '1/2 cup chopped onion',
    ingr4: '1 pound lean ground beef',
    ingr5: '1 15-ounce can no-salt-added petite diced tomatoes',
    ingr6: '2 tablespoons dill relish plus 1 teaspoon, divided',
    ingr7: '2 tablespoons ketchup, divided',
    ingr8: '1 tablespoon prepared yellow mustard',
    ingr9: '3/4 teaspoon salt',
    ingr10: '1/4 teaspoon ground pepper',
    ingr11: '1 cup shredded Cheddar cheese',
    ingr12: '3 tablespoons mayonnaise',
    ingr13: '1 1/2 cups shredded iceberg or romaine lettuce',
    ingr14: null,
    ingr15: null,
    ingr16: null,
    ingr17: null,
    ingr18: null,
    step1: 'Step 1',
    descriptionStep1:
        'Bring a large pot of water to a boil. Add rotini and cook according to package directions. Drain and set aside.',
    imageStep1: null,
    step2: 'Step 2',
    descriptionStep2:
        'Heat oil in a large skillet over medium heat. Add onion and cook, stirring, until softened, about 3 minutes. Add ground beef and cook, stirring, until no longer pink, about 7 minutes. Stir in tomatoes and their juices, 2 tablespoons relish, 1 tablespoon ketchup, mustard, salt and pepper; bring to a simmer and cook, stirring, until the liquid has reduced by half, about 3 minutes. Stir in the rotini, then sprinkle with cheese. Remove from heat, cover and let stand until the cheese has melted, about 5 minutes.',
    imageStep2: 'assets/images/food10st2.png',
    step3: 'Step 3',
    descriptionStep3:
        'Meanwhile, stir mayonnaise and the remaining 1 tablespoon ketchup and 1 teaspoon relish together in a small bowl.',
    imageStep3: 'assets/images/food10st3.png',
    step4: 'Step 4',
    descriptionStep4:
        'Serve the casserole sprinkled with lettuce and drizzled with the sauce.',
    imageStep4: 'assets/images/food10st4.png',
    step5: null,
    descriptionStep5: null,
    imageStep5: null,
    randoName: 'Nutrition Information',
    randoDescription: '''Serving Size: 1 1/3 cups

Calories 442, Fat 23g, Saturated Fat 8g, Cholesterol 71mg, Carbohydrates 35g, Total Sugars 5g, Added Sugars 1g, Protein 26g, Fiber 5g, Sodium 707mg, Potassium 488mg''',
    calories: null,
    fat: null,
    carbs: null,
    protein: null,
  ),
  FoodModel(
    recipe: '11th recipe',
    recipeApp: 'Recipe 11',
    imagGlav: 'assets/images/food11.png',
    title: 'Baked Fish Tacos with Avocado',
    description:
        'Instead of deep-frying, the fish fillets in this quick-and-easy 5-ingredient recipe are coated with a flavorful seasoning blend and baked. Several varieties of flaky white fish can be used for these tacos. When you go to the market to purchase fish, the best strategy is to be flexible and choose the variety that looks freshest that day.',
    time1: 'PREP Time:',
    timeDes1: '20 mins',
    time2: 'Additional Time:',
    timeDes2: '5 mins',
    time3: 'Total Time:',
    timeDes3: '25 mins',
    time4: 'Servings:',
    timeDes4: '4',
    time5: 'Yield:',
    timeDes5: '8 tacos',
    imageIngredient: null,
    ingr1: '1 tablespoon avocado oil',
    ingr2: '2 teaspoons no-salt-added Mexican-style seasoning blend',
    ingr3: '½ teaspoon salt',
    ingr4:
        '1 pound flaky white fish fillets, such as cod, haddock or mahi mahi, cut into 8 or 16 pieces',
    ingr5: '1 avocado, cut into 16 slices',
    ingr6: '½ cup pico de gallo',
    ingr7: '8 corn tortillas, warmed',
    ingr8: null,
    ingr9: null,
    ingr10: null,
    ingr11: null,
    ingr12: null,
    ingr13: null,
    ingr14: null,
    ingr15: null,
    ingr16: null,
    ingr17: null,
    ingr18: null,
    step1: 'Step 1',
    descriptionStep1:
        'Preheat oven to 400 degrees F. Coat a large rimmed baking sheet with cooking spray.',
    imageStep1: null,
    step2: 'Step 2',
    descriptionStep2:
        'Stir oil, seasoning blend and salt together in a medium bowl. Add fish and toss to coat. Transfer to the prepared baking sheet and bake until the fish flakes easily, about 10 minutes, depending on thickness.',
    imageStep2: null,
    step3: 'Step 3',
    descriptionStep3:
        'To assemble tacos, place 1 or 2 pieces of the fish, 2 slices avocado and 1 tablespoon pico de gallo in each tortilla.',
    imageStep3: null,
    step4: null,
    descriptionStep4: null,
    imageStep4: null,
    step5: null,
    descriptionStep5: null,
    imageStep5: null,
    randoName: null,
    randoDescription: null,
    calories: '296',
    fat: '13g',
    carbs: '29g',
    protein: '19g',
  ),
  FoodModel(
    recipe: '12th recipe',
    recipeApp: 'Recipe 12',
    imagGlav: 'assets/images/food12.png',
    title: 'Mom\'s Chili',
    description:
        'This healthy basic beef chili recipe is well worth doubling so you can throw a batch in the freezer. Serve topped with diced red onion, sliced scallions, shredded cheese and your favorite hot sauce.',
    time1: 'Cook Time:',
    timeDes1: '45 mins',
    time2: 'Additional Time:',
    timeDes2: '1 hr 30 mins',
    time3: 'Total Time:',
    timeDes3: '2 hrs 15 mins',
    time4: 'Servings:',
    timeDes4: '8',
    time5: 'Yield:',
    timeDes5: '8 servings',
    imageIngredient: null,
    ingr1: '1 tablespoon canola oil',
    ingr2: '3 cups finely chopped onions',
    ingr3: '2 cups finely chopped green bell peppers',
    ingr4: '1 clove garlic, minced',
    ingr5: '2 pounds lean ground beef (90% or leaner)',
    ingr6: '1 cup water',
    ingr7: '1 14-ounce can no-salt-added diced tomatoes',
    ingr8: '1 6-ounce can tomato paste',
    ingr9: '2 bay leaves',
    ingr10: '¼ cup chili powder',
    ingr11: '1 teaspoon ground cumin',
    ingr12: '1 teaspoon red-wine vinegar',
    ingr13: '¾ teaspoon salt',
    ingr14: 'Ground pepper to taste',
    ingr15: 'Pinch of cayenne pepper',
    ingr16: '1 15-ounce can kidney beans, rinsed',
    ingr17: null,
    ingr18: null,
    step1: 'Step 1',
    descriptionStep1:
        'Heat oil in a large pot over medium-high heat. Add onions, peppers and garlic and cook, stirring frequently, until tender, about 15 minutes. Add beef and cook, breaking it up with a spoon, until no longer pink, 7 to 8 minutes. Add water, tomatoes and their juice, tomato paste, bay leaves, chili powder, cumin, vinegar, salt, pepper and cayenne; stir well to combine. Cover and simmer over low heat for 1 hour.',
    imageStep1: null,
    step2: 'Step 2',
    descriptionStep2:
        'Stir in beans and cook, uncovered, for 30 minutes more. Remove bay leaves before serving.',
    imageStep2: null,
    step3: null,
    descriptionStep3: null,
    imageStep3: null,
    step4: null,
    descriptionStep4: null,
    imageStep4: null,
    step5: null,
    descriptionStep5: null,
    imageStep5: null,
    randoName: 'Tips',
    randoDescription:
        'Make Ahead Tip: Refrigerate for up to 5 days or freeze for up to 6 months.',
    calories: '303',
    fat: '13g',
    carbs: '23g',
    protein: '27g',
  ),
  FoodModel(
    recipe: '13th recipe',
    recipeApp: 'Recipe 13',
    imagGlav: 'assets/images/food13.png',
    title: 'Lemon-Garlic Chicken Casserole',
    description:
        'This chicken and rice casserole packs in the protein plus offers plenty of fiber from brown rice and broccoli for a well-rounded meal in one pot. Chicken thighs are meaty and tender, but feel free to swap them out for chicken breast if you prefer.',
    time1: 'Active Time:',
    timeDes1: '20 mins',
    time2: 'Total Time:',
    timeDes2: '1 hr 15 mins',
    time3: 'Servings:',
    timeDes3: '4 servings',
    time4: null,
    timeDes4: null,
    time5: null,
    timeDes5: null,
    imageIngredient: 'assets/images/food13ingr.png',
    ingr1:
        '1 pound boneless, skinless chicken thighs, cut into 1 1/2-inch pieces',
    ingr2: '1 1/2 teaspoons grated lemon zest, plus more for garnish',
    ingr3: '3 tablespoons lemon juice',
    ingr4: '1 1/2 tablespoons finely chopped garlic',
    ingr5: '1 tablespoon fresh thyme leaves, plus more for garnish',
    ingr6: '2 tablespoons extra-virgin olive oil, divided',
    ingr7: '1/2 cup chopped shallot',
    ingr8: '1 cup long-grain brown rice, rinsed',
    ingr9: '1 1/2 cups unsalted chicken broth',
    ingr10: '3/4 cup whole milk',
    ingr11: '1 (1/2-oz.) Parmesan cheese rind (optional)',
    ingr12: '3/4 teaspoon salt',
    ingr13: '1/2 teaspoon ground pepper',
    ingr14:
        '12 ounces fresh broccoli florets, cut into 3/4-inch pieces (about 5 cups)',
    ingr15: '2 1/2 tablespoons grated Parmesan cheese',
    ingr16: null,
    ingr17: null,
    ingr18: null,
    step1: 'Step 1',
    descriptionStep1:
        'Place chicken, lemon zest, lemon juice, garlic and thyme in a large zip-top plastic bag or bowl. Let stand at room temperature for 15 minutes.',
    imageStep1: 'assets/images/food13st1.png',
    step2: 'Step 2',
    descriptionStep2:
        'Preheat oven to 350°F. Remove chicken from marinade; reserve marinade.',
    imageStep2: null,
    step3: 'Step 3',
    descriptionStep3:
        'Heat 1 tablespoon oil in a large high-sided oven-safe skillet over medium-high heat. Add the chicken; cook until browned on both sides, about 2 minutes per side. Transfer to a plate.',
    imageStep3: 'assets/images/food13st3.png',
    step4: 'Step 4',
    descriptionStep4:
        'Add the remaining 1 tablespoon oil to the drippings in the pan; reduce heat to medium. Add shallot; cook, stirring occasionally, until translucent, about 2 minutes. Add rice; cook, stirring constantly, until lightly toasted, about 1 minute. Add broth and milk, stirring to combine. Stir in Parmesan rind (if using), salt and pepper; bring to a simmer over medium-high heat. Stir in the chicken and the reserved marinade. Cover, transfer to the oven and bake until the liquid is mostly absorbed, about 45 minutes.',
    imageStep4: 'assets/images/food13st4.png',
    step5: 'Step 5',
    descriptionStep5:
        'Remove the skillet from the oven. Sprinkle evenly with broccoli florets. Bake, covered, until the rice and broccoli are tender, about 10 minutes. Top with Parmesan. Garnish with lemon zest and thyme leaves, if desired.',
    imageStep5: 'assets/images/food13st5.png',
    randoName: 'Nutrition Information',
    randoDescription: '''Serving Size: about 2 1/2 cups

Calories 462, Fat 16g, Saturated Fat 4g, Cholesterol 114mg, Carbohydrates 48g, Total Sugars 6g, Added Sugars 0g, Protein 33g, Fiber 5g, Sodium 697mg, Potassium 833mg''',
    calories: null,
    fat: null,
    carbs: null,
    protein: null,
  ),
  FoodModel(
    recipe: '14th recipe',
    recipeApp: 'Recipe 14',
    imagGlav: 'assets/images/food14.png',
    title: 'Creamy Chicken Noodle Soup with Rotisserie Chicken',
    description:
        'This creamy chicken noodle soup recipe has a delicious potpie feel to it. We call for rotisserie chicken to streamline your prep time—look for a nice big one with lots of breast meat on it. Pair this comforting soup with a green salad.',
    time1: 'Active Time:',
    timeDes1: '30 mins',
    time2: 'Total Time:',
    timeDes2: '30 mins',
    time3: 'Servings:',
    timeDes3: '8',
    time4: 'Yield:',
    timeDes4: '10 cups',
    time5: null,
    timeDes5: null,
    imageIngredient: null,
    ingr1: '2 tablespoons unsalted butter',
    ingr2: '1 tablespoon olive oil',
    ingr3: '2 cups chopped yellow onion (from 1 large onion)',
    ingr4: '1 cup chopped carrots (from 2 medium carrots)',
    ingr5: '1 cup chopped celery (from 2 large stalks)',
    ingr6: '1 ¾ teaspoons kosher salt',
    ingr7: '3 tablespoons all-purpose flour',
    ingr8: '4 cups unsalted chicken stock',
    ingr9: '2 cups whole milk',
    ingr10: '4 ounces uncooked whole-wheat egg noodles',
    ingr11:
        '3 cups coarsely chopped rotisserie chicken breast (from 2 rotisserie chickens)',
    ingr12: '1 cup frozen green peas',
    ingr13: null,
    ingr14: null,
    ingr15: null,
    ingr16: null,
    ingr17: null,
    ingr18: null,
    step1: 'Step 1',
    descriptionStep1:
        'Melt butter with olive oil in a large Dutch oven over medium-high heat. Add onion, carrots, celery and salt and cook, stirring often, until vegetables are slightly softened, 6 to 8 minutes. Add flour and stir to coat. Stir in stock and milk and let the mixture come to a boil. Add uncooked noodles to the boiling mixture. Cover and cook until noodles are al dente, about 8 minutes. Stir in chicken and peas and cook until pasta reaches desired doneness and chicken and peas are warmed through, about 1 to 2 more minutes. Serve immediately.',
    imageStep1: 'assets/images/food14.png',
    step2: null,
    descriptionStep2: null,
    imageStep2: null,
    step3: null,
    descriptionStep3: null,
    imageStep3: null,
    step4: null,
    descriptionStep4: null,
    imageStep4: null,
    step5: null,
    descriptionStep5: null,
    imageStep5: null,
    randoName: 'Equipment',
    randoDescription: 'Large Dutch oven',
    calories: '258',
    fat: '9g',
    carbs: '24g',
    protein: '23g',
  ),
  FoodModel(
    recipe: '15th recipe',
    recipeApp: 'Recipe 15',
    imagGlav: 'assets/images/food15.png',
    title: 'Gluten-Free Eggplant Parmesan',
    description:
        'This cheesy baked eggplant Parmesan has no breading, which means it\'s easier to make than the traditional version. There\'s no dredging or frying—instead, the eggplant is roasted until tender before being layered in the casserole dish with a tangy homemade tomato sauce, mozzarella and Parmesan cheese. And without breading, this satisfying eggplant Parmesan is also gluten-free.',
    time1: 'PREP Time:',
    timeDes1: '35 mins',
    time2: 'Additional Time:',
    timeDes2: '35 mins',
    time3: 'Total Time:',
    timeDes3: '1 hr 10 mins',
    time4: 'Servings:',
    timeDes4: '8',
    time5: 'Yield:',
    timeDes5: '1 9x13-inch dish',
    imageIngredient: null,
    ingr1:
        '2 (1 pound) eggplants, trimmed and cut crosswise into 1/2-inch-thick rounds',
    ingr2: '¾ teaspoon salt, divided',
    ingr3: '½ teaspoon ground pepper, divided',
    ingr4: '2 tablespoons extra-virgin olive oil',
    ingr5: '1 cup chopped onion',
    ingr6: '2 cloves garlic, minced',
    ingr7: '1 (28 ounce) can no-salt-added crushed tomatoes',
    ingr8: '¼ cup dry red wine',
    ingr9: '1 teaspoon dried basil',
    ingr10: '1 teaspoon dried oregano',
    ingr11: '1 ½ cups shredded part-skim mozzarella cheese',
    ingr12: '½ cup grated Parmesan cheese',
    ingr13: 'Thinly sliced fresh basil for garnish',
    ingr14: null,
    ingr15: null,
    ingr16: null,
    ingr17: null,
    ingr18: null,
    step1: 'Step 1',
    descriptionStep1:
        'Preheat oven to 400 degrees F. Coat 2 large baking sheets with cooking spray.',
    imageStep1: null,
    step2: 'Step 2',
    descriptionStep2:
        'Arrange eggplant slices on the prepared pans. Sprinkle with 1/4 teaspoon each salt and pepper. Roast until tender, about 20 minutes.',
    imageStep2: null,
    step3: 'Step 3',
    descriptionStep3:
        'Meanwhile, heat oil in a large skillet over medium heat. Add onion and cook, stirring, until softened, about 4 minutes. Add garlic and cook for 1 minute. Add tomatoes, wine, basil, oregano, 1/4 teaspoon salt and the remaining 1/4 teaspoon pepper; bring to a simmer. Reduce heat to medium-low and cook, stirring occasionally, until thickened, about 10 minutes.',
    imageStep3: null,
    step4: 'Step 4',
    descriptionStep4:
        'Spread about 1 cup of the sauce in a 9-by-13-inch baking dish. Arrange half the eggplant slices on the sauce. Top with 1 cup sauce and sprinkle with half the mozzarella and half the Parmesan. Repeat with the remaining ingredients to make one more layer.',
    imageStep4: null,
    step5: 'Step 5',
    descriptionStep5:
        'Bake until the sauce is bubbling around the edges and the cheese has browned in spots, about 25 minutes. Let cool for 10 minutes. Sprinkle with basil before serving, if desired.',
    imageStep5: null,
    randoName: null,
    randoDescription: null,
    calories: '192',
    fat: '9g',
    carbs: '16g',
    protein: '10g',
  ),
  FoodModel(
    recipe: '16th recipe',
    recipeApp: 'Recipe 16',
    imagGlav: 'assets/images/food16.png',
    title: 'Black Bean Tacos',
    description:
        'Mixing mashed canned beans with whole beans and seasonings makes an incredibly simple taco filling from your pantry. Top these speedy five-ingredient tacos with lettuce, tomato and salsa or any of your favorite taco toppings.',
    time1: 'PREP Time:',
    timeDes1: '10 mins',
    time2: 'Additional Time:',
    timeDes2: '15 mins',
    time3: 'Total Time:',
    timeDes3: '25 mins',
    time4: 'Servings:',
    timeDes4: '4',
    time5: 'Yield:',
    timeDes5: '8 tacos',
    imageIngredient: null,
    ingr1: '2 (15 ounce) cans black beans, rinsed',
    ingr2: '1 teaspoon ground cumin',
    ingr3: '½ teaspoon garlic powder',
    ingr4: '8 hard taco shells',
    ingr5: '¾ cup shredded Mexican cheese blend',
    ingr6: null,
    ingr7: null,
    ingr8: null,
    ingr9: null,
    ingr10: null,
    ingr11: null,
    ingr12: null,
    ingr13: null,
    ingr14: null,
    ingr15: null,
    ingr16: null,
    ingr17: null,
    ingr18: null,
    step1: 'Step 1',
    descriptionStep1: 'Preheat oven to 325 degrees F.',
    imageStep1: null,
    step2: 'Step 2',
    descriptionStep2:
        'Mash half of the beans in a large bowl. Add whole beans, cumin and garlic powder; stir to combine. Fill each taco shell with about 1/3 cup of the bean mixture. Top with cheese. Place the filled tacos on a baking sheet and bake until the beans are hot and the cheese is melted, 12 to 15 minutes.',
    imageStep2: null,
    step3: null,
    descriptionStep3: null,
    imageStep3: null,
    step4: null,
    descriptionStep4: null,
    imageStep4: null,
    step5: null,
    descriptionStep5: null,
    imageStep5: null,
    randoName: null,
    randoDescription: null,
    calories: '328',
    fat: '11g',
    carbs: '42g',
    protein: '15g',
  ),
  FoodModel(
    recipe: '17th recipe',
    recipeApp: 'Recipe 17',
    imagGlav: 'assets/images/food17.png',
    title: 'Creamy Mac & Cheese Soup',
    description:
        'A package of frozen pureed winter squash adds sweetness and good nutrition—namely vitamin A, potassium and fiber—to this soup version of a family favorite, mac and cheese. It also lends its orange color to the soup, making it seem cheesier without actually adding more cheese. Feel free to swap in your favorite shape of medium-size pasta for the elbow macaroni. Using convenience items like frozen squash means that this healthy kid-friendly dinner takes just 30 minutes to prep.',
    time1: 'PREP Time:',
    timeDes1: '30 mins',
    time2: 'Total Time:',
    timeDes2: '30 mins',
    time3: 'Servings:',
    timeDes3: '8',
    time4: 'Yield:',
    timeDes4: '10 cups',
    time5: null,
    timeDes5: null,
    imageIngredient: null,
    ingr1: '1 ½ cups whole-wheat elbow macaroni',
    ingr2: '3 tablespoons unsalted butter',
    ingr3: '3 tablespoons all-purpose flour',
    ingr4: '2 teaspoons Dijon mustard',
    ingr5: '4 cups low-sodium chicken broth',
    ingr6: '1 (10 ounce) box frozen pureed winter squash, thawed slightly',
    ingr7: '2 cups half-and-half',
    ingr8: '1 (8 ounce) package reduced-fat cream cheese, cubed and softened',
    ingr9: '1 ½ cups shredded Cheddar cheese',
    ingr10: '2 teaspoons cornstarch',
    ingr11: '2 teaspoons white-wine vinegar',
    ingr12: '¼ teaspoon ground pepper',
    ingr13: 'Sliced chives for garnish',
    ingr14: null,
    ingr15: null,
    ingr16: null,
    ingr17: null,
    ingr18: null,
    step1: 'Step 1',
    descriptionStep1:
        'Cook macaroni according to package directions. Drain and set aside.',
    imageStep1: null,
    step2: 'Step 2',
    descriptionStep2:
        'Meanwhile, melt butter in a large pot over medium heat. Add flour and mustard and whisk for 2 minutes. Gradually add broth, stirring constantly. Bring to a boil.',
    imageStep2: null,
    step3: 'Step 3',
    descriptionStep3:
        'Add squash and return to a boil. Stir in half-and-half and bring to a simmer. Add cream cheese, whisking constantly until it is melted. Remove from heat.',
    imageStep3: null,
    step4: 'Step 4',
    descriptionStep4:
        'Combine Cheddar and cornstarch in a medium bowl, tossing to coat evenly. Slowly add the cheese to the soup, stirring constantly until melted. Stir in the macaroni, vinegar and pepper. Top with chives, if desired.',
    imageStep4: null,
    step5: null,
    descriptionStep5: null,
    imageStep5: null,
    randoName: null,
    randoDescription: null,
    calories: '381',
    fat: '26g',
    carbs: '25g',
    protein: '15g',
  ),
  FoodModel(
    recipe: '18th recipe',
    recipeApp: 'Recipe 18',
    imagGlav: 'assets/images/food18.png',
    title: '''Air-Fryer 'Fried' Chicken Thighs''',
    description:
        'Air fryers need a lot less oil to create a deep-fried, crispy crust. Here, chicken thighs are marinated in buttermilk and dredged in a simple breadcrumb coating. With the help of a little cooking spray, they cook up nice and crispy with a lot less fat. Serve them with your favorite dipping sauce or slice them up to top a salad.',
    time1: 'Active Time:',
    timeDes1: '15 mins',
    time2: 'Additional Time:',
    timeDes2: '4 hrs 15 mins',
    time3: 'Total Time:',
    timeDes3: '4 hrs 30 mins',
    time4: 'Servings:',
    timeDes4: '4',
    time5: 'Yield:',
    timeDes5: '4 servings',
    imageIngredient: null,
    ingr1: '2 cups buttermilk',
    ingr2: '1 tablespoon hot sauce, such as Frank\'s RedHot',
    ingr3: '2 cloves garlic, crushed',
    ingr4: '4 boneless, skinless chicken thighs (about 1 pound total), trimmed',
    ingr5: '½ cup all-purpose flour',
    ingr6: '1 teaspoon garlic powder',
    ingr7: '½ teaspoon salt',
    ingr8: '½ teaspoon ground pepper',
    ingr9: '2 large eggs, lightly beaten',
    ingr10: '1 cup whole-wheat breadcrumbs',
    ingr11: 'Cooking spray',
    ingr12: null,
    ingr13: null,
    ingr14: null,
    ingr15: null,
    ingr16: null,
    ingr17: null,
    ingr18: null,
    step1: 'Step 1',
    descriptionStep1:
        'Combine buttermilk, hot sauce and garlic in a medium nonreactive bowl. Add chicken thighs. Cover and marinate for at least 4 hours or overnight.',
    imageStep1: null,
    step2: 'Step 2',
    descriptionStep2:
        'Combine flour, garlic powder, salt and pepper in a shallow dish. Add eggs to another shallow dish and breadcrumbs to a third shallow dish.',
    imageStep2: null,
    step3: 'Step 3',
    descriptionStep3:
        'Working one at a time, remove the chicken thighs from the marinade. Coat with the flour mixture, then the egg. Finally, coat both sides with breadcrumbs. Coat both sides of the chicken with cooking spray.',
    imageStep3: null,
    step4: 'Step 4',
    descriptionStep4:
        'Lightly coat the basket of the air fryer with cooking spray. Place the chicken thighs in a single layer in the basket. (Depending on the size of your air fryer, you may have to cook in batches.)',
    imageStep4: null,
    step5: 'Step 5',
    descriptionStep5:
        'Cook the chicken at 400 degrees F until an instant-read thermometer inserted in the center of the chicken registers 165 degrees F, turning the thighs over halfway through, about 16 minutes. (If cooking in batches, cooking time for the second batch may be shorter.)',
    imageStep5: 'assets/images/food18.png',
    randoName: null,
    randoDescription: null,
    calories: '353',
    fat: '18g',
    carbs: '20g',
    protein: '27g',
  ),
  FoodModel(
    recipe: '19th recipe',
    recipeApp: 'Recipe 19',
    imagGlav: 'assets/images/food19.png',
    title: 'Easy Lasagna',
    description:
        'This classic beef lasagna recipe is easy to make and will be ready to eat in just over an hour.',
    time1: 'Prep Time:',
    timeDes1: '30 mins',
    time2: 'Additional Time:',
    timeDes2: '35 mins',
    time3: 'Total Time:',
    timeDes3: '1 hr 5 mins',
    time4: 'Servings:',
    timeDes4: '8',
    time5: 'Yield:',
    timeDes5: '8 servings',
    imageIngredient: null,
    ingr1: '12 ounces lean ground beef',
    ingr2: '1 medium onion, chopped (1/2 cup)',
    ingr3: '1 medium carrot, finely chopped (1/2 cup)',
    ingr4: '2 cloves garlic, minced',
    ingr5: '1 (15 ounce) can no-salt-added tomato sauce',
    ingr6: '1 (6 ounce) can no-salt-added tomato paste',
    ingr7: '½ cup water',
    ingr8: '1 teaspoon dried Italian seasoning, crushed',
    ingr9: '¼ teaspoon ground pepper',
    ingr10: '9 lasagna noodles',
    ingr11: '1 egg, beaten',
    ingr12:
        '1 (15 ounce) container light ricotta cheese or low-fat cottage cheese, drained',
    ingr13: '1 cup shredded part-skim mozzarella cheese (4 ounces)',
    ingr14: '¼ cup grated Parmesan or Romano cheese (1 ounce)',
    ingr15: '2 tablespoons chopped fresh basil',
    ingr16: null,
    ingr17: null,
    ingr18: null,
    step1: 'Step 1',
    descriptionStep1:
        'Preheat oven to 375 degrees F. For sauce, cook ground beef, onion, carrot, and garlic in a large saucepan over medium-high heat until meat is brown and vegetables are tender. Drain off fat. Stir in tomato sauce, tomato paste, the water, Italian seasoning, and pepper. Bring to boiling; reduce heat. Cover and simmer for 10 minutes, stirring occasionally.',
    imageStep1: null,
    step2: 'Step 2',
    descriptionStep2:
        'Meanwhile, cook lasagna noodles according to package directions. Drain the noodles; rinse with cold water. Drain well; set aside.',
    imageStep2: null,
    step3: 'Step 3',
    descriptionStep3:
        'Lightly coat a 2-quart rectangular baking dish with cooking spray. For cheese filling, stir together the egg and ricotta (or cottage) cheese in a small bowl.',
    imageStep3: null,
    step4: 'Step 4',
    descriptionStep4:
        'Layer three noodles in the prepared baking dish. Spread with one-third of the cheese filling. Top with one-third of the sauce and one-third of the mozzarella cheese. Repeat layers twice. Sprinkle with Parmesan (or Romano).',
    imageStep4: null,
    step5: 'Step 5',
    descriptionStep5:
        'Bake, covered with foil, for 20 minutes. Uncover and bake for 5 minutes more or until heated through. Let stand for 10 minutes before serving. If desired, sprinkle with basil.',
    imageStep5: null,
    randoName: null,
    randoDescription: null,
    calories: '309',
    fat: '9g',
    carbs: '33g',
    protein: '9g',
  ),
  FoodModel(
    recipe: '20th recipe',
    recipeApp: 'Recipe 20',
    imagGlav: 'assets/images/food20.png',
    title: 'Pork Chops with Creamy Mushroom Sauce',
    description:
        'These seared pork chops are topped with a rich and creamy mushroom sauce that gets flavored with fresh herbs.',
    time1: 'Cook Time:',
    timeDes1: '30 mins',
    time2: 'Total Time:',
    timeDes2: '30 mins',
    time3: 'Servings:',
    timeDes3: '4',
    time4: 'Yield:',
    timeDes4: '''4 servings,
1 pork chop & about 1/3
cup sauce each''',
    time5: null,
    timeDes5: null,
    imageIngredient: null,
    ingr1: '4 bone-in pork chops, 1/2-3/4 inch thick (about 2 pounds), trimmed',
    ingr2: '½ teaspoon salt, divided',
    ingr3: '½ teaspoon freshly ground pepper',
    ingr4: '3 tablespoons extra-virgin olive oil, divided',
    ingr5: '⅓ cup minced shallots',
    ingr6:
        '8 ounces sliced mixed mushrooms, such as cremini, shiitake & oyster',
    ingr7: '½ cup dry white wine',
    ingr8: '⅓ cup half-and-half',
    ingr9: '½ cup chopped fresh herbs, such as chives, tarragon and/or parsley',
    ingr10: null,
    ingr11: null,
    ingr12: null,
    ingr13: null,
    ingr14: null,
    ingr15: null,
    ingr16: null,
    ingr17: null,
    ingr18: null,
    step1: 'Step 1',
    descriptionStep1:
        'Sprinkle pork chops with 1/4 teaspoon salt and pepper. Heat 1 tablespoon oil in a large skillet, preferably cast iron, over medium-high heat. Reduce the heat to medium and add 2 pork chops. Cook, turning once, until cooked through, 5 to 7 minutes. Remove to a plate and tent with foil. Repeat with another 1 tablespoon oil and the remaining chops.',
    imageStep1: null,
    step2: 'Step 2',
    descriptionStep2:
        'Add the remaining 1 tablespoon oil to the pan. Add shallots and mushrooms; cook, stirring frequently until the mushrooms are browned, 2 to 4 minutes. Add wine and the remaining 1/4 teaspoon salt; cook, stirring up any browned bits, until the liquid is mostly evaporated, 1 to 3 minutes. Stir in half-and-half and herbs; cook until bubbling, about 1 minute more. Serve the chops with the mushroom sauce.',
    imageStep2: null,
    step3: null,
    descriptionStep3: null,
    imageStep3: null,
    step4: null,
    descriptionStep4: null,
    imageStep4: null,
    step5: null,
    descriptionStep5: null,
    imageStep5: null,
    randoName: null,
    randoDescription: null,
    calories: '357',
    fat: '22g',
    carbs: '6g',
    protein: '29g',
  ),
];
